github/india

Students/EXTERNSHIPS.md
Updated Externship.md with Summer 2022 details.
=> Updated Externship.md Summer Cohort 2022

website/data/open-source/projects.yml
---
[Doggo](https://doggo.mrkaran.dev/) is a helpful tool for querying DNS servers and getting a human readable output.
=> chore: (projects): Add doggo

website/data/open-source/projects.yml
---
This [project](https://circuitverse.org/) is currently helping lakhs of students and teachers around the world to learn and teach logical circuits. 
---
=> Add CircuitVerse to the projects list

website/data/open-source/maintainers.yml
---
- https://github.com/layer5io/layer5
- https://github.com/meshery/meshery
- https://github.com/meshery/meshery.io
- https://github.com/service-mesh-patterns/service-mesh-patterns
---
=> Add "Nikhil-Ladha" to maintainers list

website/data/open-source/projects.yml
An MQTT client and broker development kit built in rust-lang
---
> rumqtt is an MQTT client library and an embeddable broker that are both built in the rust programming language.
> I am on the team that maintains rumqtt.
---
=> feat: include rumqtt

website/data/open-source/maintainers.yml
---
> Changing my state from Karnataka to Kerala
---
=> Update state in maintainers list

website/data/open-source/projects.yml
---
I am from India and started the project. 
20 of 109 contributors to Ockam, so far, are from India.
We add new "good first issue"s every week and I would love to encourage even more contributions from India.
=> Add Ockam to Open Source projects list

website/data/open-source/projects.yml
Added LitmusChaos project under Developer Productivity & Tools category
---
Litmus is an end-to-end chaos engineering platform for cloud-native infrastructure and applications. Cloud-native SREs, QA teams, and developers use Litmus to design, orchestrate and analyze chaos in their environments.
- Litmus is a CNCF incubating project
- With a regular monthly release cadence, it has been developing for over 4 years with the latest 2.13 stable version
- Litmus has 600K+ installations, 919K+ experiment runs; a 30x usage growth in the last 3 quarters, 58 chaos experiments, and 150+ contributors with the most active contributions from the Indian developer community
- The project has amassed a total of 3281 stargazers
Project Homepage: …
=> Added LitmusChaos project

website/data/open-source/maintainers.yml
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
requirements:
---
https://github.com/humblec , I am a maintainer in various open source projects which include kubernetes, glusterfs, ceph..etc
---
=> update maintainers list

website/data/open-source/projects.yml
---
> Make Highly Customized Boxes in CLI. Notably used by [kubernetes/minikube](https://github.com/kubernetes/minikube/blob/master/go.mod#L8). Other importers can be found [here](https://pkg.go.dev/github.com/Delta456/box-cli-maker/v2?tab=importedby)
> https://github.com/Delta456/box-cli-maker
---
=> projects.yml: add box-cli-maker project

website/data/open-source/projects.yml
---
SAML Jackson addresses Enterprise security through a secure implementation of SAML and OIDC from a service provider's perspective. We believe this will be useful for a lot of developers and startups in the Indian ecosystem.
=> Adding SAML Jackson from BoxyHQ

website/data/open-source/maintainers.yml, website/data/open-source/projects.yml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19yslDDHiXS3kgeHbc9X8Ox2Z5UrPVq6k%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=l_z4N9U)
---
> One of the best resources to learn DevOps
> https://github.com/rohitg00/DevOpsCommunity
> https://github.com/rohitg00/devops-twitter-bot
> https://github.com/rohitg00/DevOps_Books
---
=> DevOps Community added and maintainer too

website/data/open-source/maintainers.yml
Adding myself to the list
---
http://github.com/adonisjs/core, https://github.com/japa/runner, http://github.com/edge-js/edge
---
=> Adding Harminder Virk (myself)

website/data/open-source/maintainers.yml
- [✔] I followed the contributing guidelines: <https://github.com/github/india/blob/main/CONTRIBUTING.md>.
- [✔] Adding/updating maintainer/s
---
- [✔] Maintainer's location on their GitHub profile indicates as India
- [✔] Maintainer has approved this PR to be included on the website
> [markdownify](https://github.com/amitmerchant1990/electron-markdownify), [reverie](https://github.com/amitmerchant1990/reverie), [pomolectron](https://github.com/amitmerchant1990/pomolectron), [notepad](https://github.com/amitmerchant1990/notepad)
=> Add amitmerchant1990

website/data/open-source/projects.yml
---
> Meshery is the most popular project on the LFX Mentorship program and receives most of the significant contributions from India.
---
=> [Projects] Add Meshery to Open source projects list

website/data/open-source/projects.yml
---
> winkNLP is a JavaScript library for Natural Language Processing that is slowly gaining popularity. The contributors are primarily from India.
---
=> Add winkNLP to project list

website/data/open-source/projects.yml
Added LambdaTest/test-at-scale for Testing
---
Testing is an important category in DevOps especially in the continuous integration/feedback process. Test-At-Scale open source projects helps developers derive insights from the development projects in their unit test case cycle.
---
=> Update projects.yml to add Testing Category

website/data/open-source/maintainers.yml, website/data/open-source/projects.yml
---
>  Privado is an open-source, free, and one-stop solution to automate compliance with privacy laws like GDPR, HIPAA, SOC, and ISO compliance controls and manage privacy and data security threats in the code. Privado is a one-of-a-kind tool that discovers dataflows across applications to detect Data Sharing with Third Parties, Storages, Internal APIs, Collections, and Sensitive Data Leakages in a codebase. More information can be found [here](https://www.privado.ai/open-source).
[Privado-Inc/privado](https://github.com/Privado-Inc/privado)
> Adding both maintainer & project
---
**Please note: we will close your PR without comment if you do not check the boxes above and …
=> Add privado project & maintainer

website/data/open-source/projects.yml
---
> The project has over 50 contributors from India, and has over 4.8K stars!
- [] Maintainer's location on their GitHub profile indicates as India
---
=> added Activeloopai/Hub to the list of DS projects

website/data/open-source/maintainers.yml, website/data/open-source/projects.yml
This is the project being added: https://github.com/nikochiko/autosaved
---
It's a useful devtool with a compelling use-case, that is in use by many developers
https://github.com/nikochiko/autosaved
---
=> Add nikochiko to maintainers, autosaved to projects

website/data/open-source/maintainers.yml, website/data/open-source/projects.yml
---
> react-play is an open-source web app that helps you learn ReactJS faster with a hands-on practice model. It is a collection of ReactJS projects that you can use to learn ReactJS. You can also create your projects and share them with the world. The best part is that the ReactJS experts will review your project code before it gets part of the ReactPlay app.
---
=> Add ReactPlay To Projects list

website/data/open-source/maintainers.yml
---
https://github.com/anantshri/wp-security
https://github.com/anantshri/svn-extractor
https://github.com/anantshri/Android_Security
---
=> adding anantshri to maintainers list

website/data/open-source/maintainers.yml
---
https://github.com/one-aalam/svelte-starter-kit
https://github.com/one-aalam/remix-starter-kit
https://github.com/one-aalam/next-starter-kit
https://github.com/one-aalam/nuxt-starter-kit
https://github.com/one-aalam/astro-ink
https://github.com/one-aalam/bun-tea
https://github.com/one-aalam/awesome-solid-js
https://github.com/one-aalam/awesome-svelte-kit
https://github.com/one-aalam/awesome-astro
and more...
---
**Please note: we will close your PR without comment if you do not check the boxes above and …
=> Add `one-aalam` to maintainers list

website/data/open-source/maintainers.yml, website/data/open-source/projects.yml
- [y] I followed the contributing guidelines: <https://github.com/github/india/blob/main/CONTRIBUTING.md>.
- [y] Adding/updating open source project/s
- [y] Adding/updating maintainer/s
---
- [y] The project was built in or receives significant contributions from India
- [y] The project has at least 100 stargazers
The Face-X project need to be featured because-:
The **Face-X** project implements various face operations for ML developers as well as being contributed by more than 150+ contributors, mostly from India, so it is an important project for upcoming developers.
-> It has been a part of 10+ indian open source programs
-> It contains all the face operations in well documented folders
- [y] Maintainer's location on their GitHub …
=> Added the project Face-X and updated the maintainers.yml

website/data/open-source/projects.yml
=> added karate to projects from india

website/data/open-source/maintainers.yml
---
https://github.com/0xInfection/Awesome-WAF
https://github.com/EnableSecurity/wafw00f
https://github.com/redhuntlabs/HTTPLoot
https://github.com/0xInfection/XSRFProbe
https://github.com/0xInfection/LogMePwn
https://github.com/0xInfection/SIPTorch
https://github.com/0xInfection/PewSWITCH
... and many more!
---
=> Adding 0xinfection to the maintainers list

website/data/open-source/maintainers.yml
---
Most notable projects:
- **Blaze**: [blenderskool/blaze](https://github.com/blenderskool/blaze)
- **UnTab**: [blenderskool/untab](https://github.com/blenderskool/untab)
- **Pigmnts**: [blenderskool/pigmnts](https://github.com/blenderskool/pigmnts)
- **Diode**: [blenderskool/diode](https://github.com/blenderskool/diode)
- And [various others](https://github.com/blenderskool?tab=repositories&type=source)
---
=> Add blenderskool as maintainer from Karnataka

website/data/open-source/maintainers.yml
---
https://github.com/s0md3v/Arjun
https://github.com/s0md3v/smap
https://github.com/s0md3v/uro
https://github.com/s0md3v/AwesomeXSS
https://github.com/s0md3v/ote
https://github.com/s0md3v/hardcodes
... and many more!
---
=> Adding s0md3v to the maintainers list

website/data/open-source/maintainers.yml, website/data/open-source/projects.yml
---
> Adding both maintainer & project.
---
=> add: awesome-github-profile-readme:

.github/workflows/create-thank-you-comment.yml, .github/workflows/trigger-build.yml, .github/workflows/website-pr-validation.yml, script/website-pr-validation.rb, website/data/open-source/projects.yml
---
This PR adds new actions associated with [githubindia.com](https://githubindia.com)
---
=> Created actions associated with githubindia.com

website/data/open-source/maintainers.yml, website/data/open-source/projects.yml
---
I've been personally maintaining this project with several other projects in https://github.com/hc-oss org from some time and more people using it and more people enhancing all of this projects will be nice.
- https://github.com/hc-oss/react-multi-select-component
- https://github.com/hc-oss/react-tag-input-component
- https://github.com/hc-oss/react-web-share
---
=> added react-multi-select-component in projects

website/data/open-source/maintainers.yml, website/data/open-source/projects.yml
Signed-off-by: Saiyam Pathak <saiyam911@gmail.com>
---
This is the repo that helps people in getting ready for DevOps following the complete roadmap and sharing their journey.
https://github.com/civo/kubernetes-marketplace
https://github.com/kubesimplify/workshops-content
https://github.com/kubesimplify/tweets
Everything under https://github.com/kubesimplify/
---
**Please note: we will close your PR without comment if you do …
=> DevOps roadmap added and maintainer too

website/data/open-source/maintainers.yml
---
- https://github.com/kubernetes/website
- https://github.com/litmuschaos/litmus-docs
---
=> Add divya-mohan0209 to maintainers
